#version 450
#define LOCAL_SIZE 2
layout(local_size_x = LOCAL_SIZE, local_size_y = LOCAL_SIZE, local_size_z = 1) in;

layout(std140, set = 0, binding = 0) uniform input_block {
    vec3 vertices[4];
} src;

layout (std430, set = 1, binding = 0) buffer output_block {
    vec4 vertices[4];
} dst;

layout (std140, set = 2, binding = 0) uniform UBO_0 {
	mat4 transform;
};  

void main(void)
{
    uint i = gl_WorkGroupID.x * gl_WorkGroupSize.x * gl_WorkGroupSize.y + gl_LocalInvocationIndex;
    dst.vertices[i] = transform * vec4(src.vertices[i], 1.0);
}
