rem These commands were extracted from the output of "python.exe setup.py build --compiler=msvc", then modified to enable debug symbols: 
rem change /Ox to /Od
rem add /Zi flag to compiler flags
rem add /DEBUG flag to linker flags
mkdir build\temp.win-amd64-3.8\Release\
mkdir build\lib.win-amd64-3.8\

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe" /c /nologo /Od /Zi /W3 /GL /DNDEBUG /MD -IC:\Users\jmoguillansky\Documents\2020\Git\gopro-lib-node.gl\pynodegl\..\nodegl-env\Include -Ic:\users\jmoguillansky\documents\2020\git\gopro-lib-node.gl\nodegl-env\include -IC:\Users\jmoguillansky\AppData\Local\Programs\Python\Python38\include -IC:\Users\jmoguillansky\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcpynodegl.c /Fobuild\temp.win-amd64-3.8\Release\pynodegl.obj

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe" /DEBUG /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\jmoguillansky\Documents\2020\Git\gopro-lib-node.gl\pynodegl\..\nodegl-env\Lib /LIBPATH:c:\users\jmoguillansky\documents\2020\git\gopro-lib-node.gl\nodegl-env\libs /LIBPATH:C:\Users\jmoguillansky\AppData\Local\Programs\Python\Python38\libs /LIBPATH:C:\Users\jmoguillansky\AppData\Local\Programs\Python\Python38 /LIBPATH:c:\users\jmoguillansky\documents\2020\git\gopro-lib-node.gl\nodegl-env\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" nodegl.lib ngfx.lib pthreadVC2.lib sxplayer.lib avcodec.lib avdevice.lib avformat.lib avfilter.lib avutil.lib OpenGL32.lib gdi32.lib user32.lib d3d12.lib shader_tools.lib dxgi.lib d3dcompiler.lib shaderc_combined.lib spirv-cross-cpp.lib spirv-cross-core.lib spirv-cross-glsl.lib spirv-cross-hlsl.lib spirv-cross-msl.lib spirv-cross-reflect.lib spirv-cross-util.lib spirv-cross-c.lib /EXPORT:PyInit_pynodegl build\temp.win-amd64-3.8\Release\pynodegl.obj /OUT:build\lib.win-amd64-3.8\pynodegl.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\pynodegl.cp38-win_amd64.lib
       
copy build\lib.win-amd64-3.8\pynodegl.cp38-win_amd64.pyd .
