name: 'tests Linux'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt -y update
        #
        # python3-venv is required to prevent the following issue:
        #     The virtual environment was not created successfully because ensurepip is not
        #     available.  On Debian/Ubuntu systems, you need to install the python3-venv
        #     package using the following command.
        #
        #         apt-get install python3-venv
        #
        sudo apt -y install libsdl2-dev python3-venv
        sudo apt -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev \
          libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev ninja-build libglm-dev \
          libglfw3-dev libglew-dev renderdoc
        #Install Vulkan SDK
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.162-focal.list https://packages.lunarg.com/vulkan/1.2.162/lunarg-vulkan-1.2.162-focal.list
        sudo apt update
        sudo apt install vulkan-sdk

    - name: Build
      run: |
        make -j$(($(nproc)+1))
    - name: Run tests
      run: |
        DEBUG=yes DEBUG_GL=yes make -k -j$(($(nproc)+1)) tests

  gles2:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt -y install libsdl2-dev python3-venv
        sudo apt -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev \
          libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev ninja-build libglm-dev \
          libglfw3-dev libglew-dev renderdoc
        #Install Vulkan SDK
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.162-focal.list https://packages.lunarg.com/vulkan/1.2.162/lunarg-vulkan-1.2.162-focal.list
        sudo apt update
        sudo apt install vulkan-sdk

    - name: Build
      run: |
        make -j$(($(nproc)+1))
    - name: Run tests with OpenGLES2
      run: |
        MESA_GLES_VERSION_OVERRIDE=2.0 DEBUG=yes DEBUG_GL=yes make -k -j$(($(nproc)+1)) tests TESTS_SUITE=opengles
